(load "~/.emacs.d/ek-el-files/prog/ek-c-gen.el")
(load "~/.emacs.d/ek-el-files/prog/ek-markdown.el")
(load "~/.emacs.d/ek-el-files/prog/ek-python.el")
(load "~/.emacs.d/ek-el-files/prog/ek-octave.el")
(load "~/.emacs.d/ek-el-files/prog/ek-cmake.el")
